# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Plain Plain Text
email: inbox@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Modular tutorials for humanists to learn to use plain text.
url: "http://plain-plain-text.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: broccolini/swiss
google-code: "UA-592475-9"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
include: ["_pages"]
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
collections:
  tutorials:
    output: true
  modules:
    output: true
  whatis:
    output: true
  cheatsheets:
    output: true
defaults:
- scope:
    path: ""
    type: tutorials
  values:
    layout: tutorial
    author: muziejus
- scope:
    path: ""
    type: modules
  values:
    layout: module
    author: muziejus
- scope:
    path: ""
    type: whatis
  values:
    layout: whatis
    author: muziejus
- scope:
    path: ""
    type: cheatsheets
  values:
    layout: default
    author: muziejus

