title: Plain Plain Text
email: inbox@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Modular tutorials for humanists to learn to use plain text.
url: "http://plain-plain-text.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  plain-plain-text
github: [metadata]
google-code: "UA-592475-9"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
include: ["_pages"]
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
